
extends Spatial
var CityScn = preload("res://Scene/Object/city.scn")
var PathScn = preload("res://Scene/Object/path.scn")
var CardSlotScn = preload("res://Scene/Object/card_location.scn")

var Cities = []
var Paths = []
var Paths_node = []
var Slots = []
var Id = 1

func _ready():
	create_world()
	

func create_world():
	_add_path({ "pos": Vector3(-20.5, 0, 2), "Rotation": 15, "NbrSpace": 5, "Type": "normal", "color": colors.green, "city_A": "Pamplona", "city_B": "Paris", "color_name": "green"})
	_add_path({ "pos": Vector3(-22, 0, 2), "Rotation": 15, "NbrSpace": 5, "Type": "normal", "color": colors.blue, "city_A": "Pamplona", "city_B": "Paris", "color_name": "blue"})
	_add_path({ "pos": Vector3(-38, 0, 26), "Rotation": -50, "NbrSpace": 2, "Type": "normal", "color": colors.blue, "city_A": "Cadiz", "city_B": "Lisboa", "color_name": "blue"})
	_add_path({ "pos": Vector3(-34, 0, 23.5), "Rotation": 0, "NbrSpace": 2, "Type": "normal", "color": colors.orange, "city_A": "Madrid", "city_B": "Cadiz", "color_name": "orange"})
	_add_path({ "pos": Vector3(-36, 0, 21), "Rotation": 60, "NbrSpace": 2, "Type": "normal", "color": colors.pink, "city_A": "Lisboa", "city_B": "Madrid", "color_name": "pink"})
	_add_path({ "pos": Vector3(-27, 0, 15), "Rotation": 55, "NbrSpace": 4, "Type": "tunnel", "color": colors.black, "city_A": "Pamplona", "city_B": "Madrid", "color_name": "black"})
	_add_path({ "pos": Vector3(-26, 0, 16), "Rotation": 55, "NbrSpace": 4, "Type": "tunnel", "color": colors.white, "city_A": "Pamplona", "city_B": "Madrid", "color_name": "white"})
	_add_path({ "pos": Vector3(-26.5, 0, 22.5), "Rotation": 100, "NbrSpace": 3, "Type": "normal", "color": colors.yellow, "city_A": "Barcelona", "city_B": "Madrid", "color_name": "yellow"})
	_add_path({ "pos": Vector3(-24.5, 0, 18), "Rotation": 0, "NbrSpace": 2, "Type": "tunnel", "color": colors.grey, "city_A": "Pamplona", "city_B": "Barcelona", "color_name": "grey"})
	_add_path({ "pos": Vector3(-14, 0, 15), "Rotation": 55, "NbrSpace": 5, "Type": "normal", "color": colors.grey, "city_A": "Marseille", "city_B": "Barcelona", "color_name": "grey"})
	_add_path({ "pos": Vector3(-15, 0, 13), "Rotation": 85, "NbrSpace": 4, "Type": "normal", "color": colors.red, "city_A": "Pamplona", "city_B": "Marseille", "color_name": "red"})
	_add_path({ "pos": Vector3(-31, 0, 1), "Rotation": -20, "NbrSpace": 6, "Type": "normal", "color": colors.pink, "city_A": "Brest", "city_B": "Pamplona", "color_name": "pink"})
	_add_path({ "pos": Vector3(-30, 0, -1), "Rotation": -80, "NbrSpace": 4, "Type": "normal", "color": colors.black, "city_A": "Brest", "city_B": "Paris", "color_name": "black"})
	_add_path({ "pos": Vector3(-24, 0, -3), "Rotation": -45, "NbrSpace": 2, "Type": "normal", "color": colors.pink, "city_A": "Dieppe", "city_B": "Paris","color_name": "pink"})
	_add_path({ "pos": Vector3(-3, 0, 18), "Rotation": -15, "NbrSpace": 4, "Type": "ferry", "color": colors.grey, "city_A": "Palermo", "city_B": "Roma", "color_name": "grey"})
	_add_path({ "pos": Vector3(18, 0, 28.5), "Rotation": 90, "NbrSpace": 7, "Type": "double_ferry", "color": colors.grey, "city_A": "Palermo", "city_B": "Smyrna", "color_name": "grey"})
	_add_path({ "pos": Vector3(-12, 0, 8), "Rotation": 15, "NbrSpace": 2, "Type": "tunnel", "color": colors.pink, "city_A": "Zurich", "city_B": "Marseille", "color_name": "pink"})
	_add_path({ "pos": Vector3(-19, 0, 3), "Rotation": -30, "NbrSpace": 4, "Type": "normal", "color": colors.grey, "city_A": "Marseille", "city_B": "Paris", "color_name": "grey"})
	_add_path({ "pos": Vector3(-18, 0, 1), "Rotation": -60, "NbrSpace": 3, "Type": "tunnel", "color": colors.grey, "city_A": "Paris", "city_B": "Zurich", "color_name": "grey"})
	_add_path({ "pos": Vector3(-20, 0, -7), "Rotation": 60, "NbrSpace": 2, "Type": "normal", "color": colors.green, "city_A": "Bruxelles", "city_B": "Dieppe", "color_name": "green"})
	_add_path({ "pos": Vector3(-19.5, 0, -5), "Rotation": 15, "NbrSpace": 2, "Type": "normal", "color": colors.yellow, "city_A": "Paris", "city_B": "Bruxelles", "color_name": "yellow"})
	_add_path({ "pos": Vector3(-18, 0, -5), "Rotation": 15, "NbrSpace": 2, "Type": "normal", "color": colors.red, "city_A": "Paris", "city_B": "Bruxelles", "color_name": "red"})
	_add_path({ "pos": Vector3(-27, 0, -3), "Rotation": 75, "NbrSpace": 2, "Type": "normal", "color": colors.orange, "city_A": "Brest", "city_B": "Dieppe", "color_name": "orange"})
	_add_path({ "pos": Vector3(-23.5, 0, -11), "Rotation": 10, "NbrSpace": 3, "Type": "ferry", "color": colors.grey, "city_A": "Dieppe", "city_B": "London", "color_name": "grey"})
	_add_path({ "pos": Vector3(-25, 0, -11), "Rotation": 10, "NbrSpace": 3, "Type": "ferry", "color": colors.grey, "city_A": "Dieppe", "city_B": "London", "color_name": "grey"})
	_add_path({ "pos": Vector3(-21, 0, -13), "Rotation": -80, "NbrSpace": 2, "Type": "double_ferry", "color": colors.grey, "city_A": "Amsterdam", "city_B": "London", "color_name": "grey"})
	_add_path({ "pos": Vector3(-28.5, 0, -24), "Rotation": -20, "NbrSpace": 5, "Type": "normal", "color": colors.black, "city_A": "Edinburgh", "city_B": "London", "color_name": "black"})
	_add_path({ "pos": Vector3(-27, 0, -25), "Rotation": -20, "NbrSpace": 5, "Type": "normal", "color": colors.orange, "city_A": "Edinburgh", "city_B": "London", "color_name": "orange"})
	_add_path({ "pos": Vector3(-17, 0, -10), "Rotation": 25, "NbrSpace": 1, "Type": "normal", "color": colors.black, "city_A": "Amsterdam", "city_B": "Bruxelles", "color_name": "black"})
	_add_path({ "pos": Vector3(-12, 0, -3), "Rotation": 65, "NbrSpace": 3, "Type": "normal", "color": colors.orange, "city_A": "Paris", "city_B": "Frankfurt", "color_name": "orange"})
	_add_path({ "pos": Vector3(-12, 0, -4.5), "Rotation": 65, "NbrSpace": 3, "Type": "normal", "color": colors.white, "city_A": "Paris", "city_B": "Frankfurt", "color_name": "white"})
	_add_path({ "pos": Vector3(-16, 0, -7), "Rotation": -60, "NbrSpace": 2, "Type": "normal", "color": colors.blue, "city_A": "Bruxelles", "city_B": "Frankfurt","color_name": "blue"})
	_add_path({ "pos": Vector3(-14.5, 0, -11), "Rotation": -40, "NbrSpace": 3, "Type": "normal", "color": colors.white, "city_A": "Amsterdam", "city_B": "Frankfurt","color_name": "white"})
	_add_path({ "pos": Vector3(-9, 0, -9), "Rotation": 15, "NbrSpace": 2, "Type": "normal", "color": colors.green, "city_A": "Essen", "city_B": "Frankfurt", "color_name": "green"})
	_add_path({ "pos": Vector3(-14, 0, -12.5), "Rotation": -80, "NbrSpace": 2, "Type": "normal", "color": colors.yellow, "city_A": "Amsterdam", "city_B": "Essen", "color_name": "yellow"})
	_add_path({ "pos": Vector3(-7, 0, 1), "Rotation": 45, "NbrSpace": 2, "Type": "tunnel", "color": colors.yellow, "city_A": "Zurich", "city_B": "Munich", "color_name": "yellow"})
	_add_path({ "pos": Vector3(-9, 0, -3), "Rotation": -45, "NbrSpace": 2, "Type": "normal", "color": colors.pink, "city_A": "Frankfurt", "city_B": "Munich", "color_name": "pink"})
	_add_path({ "pos": Vector3(-9, 0, 6.5), "Rotation": -75, "NbrSpace": 2, "Type": "tunnel", "color": colors.green, "city_A": "Venezia", "city_B": "Zurich", "color_name": "green"})
	_add_path({ "pos": Vector3(-3.5, 0, 11), "Rotation": -5, "NbrSpace": 2, "Type": "normal", "color": colors.black, "city_A": "Venezia", "city_B": "Roma", "color_name": "black"})
	_add_path({ "pos": Vector3(-5, 0, 2), "Rotation": -15, "NbrSpace": 2, "Type": "tunnel", "color": colors.blue, "city_A": "Munich", "city_B": "Venezia", "color_name": "blue"})
	_add_path({ "pos": Vector3(-11, 0, 14), "Rotation": -75, "NbrSpace": 3, "Type": "tunnel", "color": colors.grey, "city_A": "Marseille", "city_B": "Roma", "color_name": "grey"})
	_add_path({ "pos": Vector3(-1, 0, 17.5), "Rotation": -65, "NbrSpace": 2, "Type": "normal", "color": colors.white, "city_A": "Brindisi", "city_B": "Roma", "color_name": "white"})
	_add_path({ "pos": Vector3(2, 0, 21), "Rotation": 15, "NbrSpace": 3, "Type": "ferry", "color": colors.grey, "city_A": "Brindisi", "city_B": "Palermo", "color_name": "grey"})
	_add_path({ "pos": Vector3(5, 0, 20.5), "Rotation": -55, "NbrSpace": 4, "Type": "ferry", "color": colors.grey, "city_A": "Athina", "city_B": "Brindisi", "color_name": "grey"})
	_add_path({ "pos": Vector3(-2, 0, 8), "Rotation": -80, "NbrSpace": 2, "Type": "normal", "color": colors.grey, "city_A": "Venezia", "city_B": "Zagrab", "color_name": "grey"})
	_add_path({ "pos": Vector3(-3.5, 0, -1), "Rotation": -75, "NbrSpace": 3, "Type": "normal", "color": colors.orange, "city_A": "Munich", "city_B": "Wien", "color_name": "orange"})
	_add_path({ "pos": Vector3(3, 0, 3), "Rotation": 5, "NbrSpace": 2, "Type": "normal", "color": colors.grey, "city_A": "Wien", "city_B": "Zagrab", "color_name": "grey"})
	_add_path({ "pos": Vector3(6, 0, 1), "Rotation": -75, "NbrSpace": 1, "Type": "normal", "color": colors.red, "city_A": "Budapest", "city_B": "Wien", "color_name": "red"})
	_add_path({ "pos": Vector3(5.5, 0, 2.5), "Rotation": -75, "NbrSpace": 1, "Type": "normal", "color": colors.white, "city_A": "Budapest", "city_B": "Wien", "color_name": "white"})
	_add_path({ "pos": Vector3(6.5, 0, 5), "Rotation": 45, "NbrSpace": 2, "Type": "normal", "color": colors.orange, "city_A": "Budapest", "city_B": "Zagrab", "color_name": "orange"})
	_add_path({ "pos": Vector3(0, 0, -8), "Rotation": -20, "NbrSpace": 4, "Type": "normal", "color": colors.green, "city_A": "Berlin", "city_B": "Wien", "color_name": "green"})
	_add_path({ "pos": Vector3(-3, 0, -9), "Rotation": 60, "NbrSpace": 3, "Type": "normal", "color": colors.black, "city_A": "Frankfurt", "city_B": "Berlin", "color_name": "black"})
	_add_path({ "pos": Vector3(-3, 0, -7.5), "Rotation": 60, "NbrSpace": 3, "Type": "normal", "color": colors.red, "city_A": "Frankfurt", "city_B": "Berlin", "color_name": "red"})
	_add_path({ "pos": Vector3(-6.5, 0, -11), "Rotation": -75, "NbrSpace": 2, "Type": "normal", "color": colors.blue, "city_A": "Essen", "city_B": "Berlin","color_name": "blue"})
	_add_path({ "pos": Vector3(3.5, 0, 11), "Rotation": -55, "NbrSpace": 3, "Type": "normal", "color": colors.red, "city_A": "Sarajevo", "city_B": "Zagrab", "color_name": "red"})
	_add_path({ "pos": Vector3(10.5, 0, 17), "Rotation": -20, "NbrSpace": 4, "Type": "normal", "color": colors.green, "city_A": "Athina", "city_B": "Sarajevo", "color_name": "green"})
	_add_path({ "pos": Vector3(10.5, 0, 15), "Rotation": -85, "NbrSpace": 2, "Type": "tunnel", "color": colors.grey, "city_A": "Sofia", "city_B": "Sarajevo", "color_name": "grey"})
	_add_path({ "pos": Vector3(15, 0, 17.5), "Rotation": 10, "NbrSpace": 3, "Type": "normal", "color": colors.pink, "city_A": "Athina", "city_B": "Sofia", "color_name": "pink"})
	_add_path({ "pos": Vector3(17, 0, 16), "Rotation": -60, "NbrSpace": 3, "Type": "normal", "color": colors.blue, "city_A": "Constantinople", "city_B": "Sofia", "color_name": "blue"})
	_add_path({ "pos": Vector3(8.5, 0, 6), "Rotation": -10, "NbrSpace": 3, "Type": "normal", "color": colors.pink, "city_A": "Sarajevo", "city_B": "Budapest", "color_name": "pink"})
	_add_path({ "pos": Vector3(10, 0, 4.5), "Rotation": -60, "NbrSpace": 4, "Type": "tunnel", "color": colors.grey, "city_A": "Budapest", "city_B": "Bucuresti", "color_name": "grey"})
	_add_path({ "pos": Vector3(17, 0, 13), "Rotation": -150, "NbrSpace": 2, "Type": "tunnel", "color": colors.grey, "city_A": "Sofia", "city_B": "Bucuresti", "color_name": "grey"})
	_add_path({ "pos": Vector3(21, 0, 11), "Rotation": -15, "NbrSpace": 4, "Type": "normal", "color": colors.yellow, "city_A": "Constantinople", "city_B": "Bucuresti", "color_name": "yellow"})
	_add_path({ "pos": Vector3(16, 0, 26), "Rotation": -70, "NbrSpace": 2, "Type": "ferry", "color": colors.grey, "city_A": "Smyrna", "city_B": "Athina", "color_name": "grey"})
	_add_path({ "pos": Vector3(23, 0, 24), "Rotation": 30, "NbrSpace": 2, "Type": "tunnel", "color": colors.grey, "city_A": "Smyrna", "city_B": "Constantinople", "color_name": "grey"})
	_add_path({ "pos": Vector3(23, 0, 28.5), "Rotation": -110, "NbrSpace": 3, "Type": "tunnel", "color": colors.orange, "city_A": "Smyrna", "city_B": "Angora", "color_name": "orange"})
	_add_path({ "pos": Vector3(26, 0, 23), "Rotation": -50, "NbrSpace": 2, "Type": "tunnel", "color": colors.grey, "city_A": "Constantinople", "city_B": "Angora", "color_name": "grey"})
	_add_path({ "pos": Vector3(32, 0, 26), "Rotation": -110, "NbrSpace": 2, "Type": "normal", "color": colors.black, "city_A": "Erzurum", "city_B": "Angora", "color_name": "black"})
	_add_path({ "pos": Vector3(39, 0, 14), "Rotation": 10, "NbrSpace": 4, "Type": "tunnel", "color": colors.red, "city_A": "Erzurum", "city_B": "Sochi", "color_name": "red"})
	_add_path({ "pos": Vector3(32, 0, 14), "Rotation": -20, "NbrSpace": 4, "Type": "double_ferry", "color": colors.grey, "city_A": "Sevastopol", "city_B": "Erzurum", "color_name": "grey"})
	_add_path({ "pos": Vector3(30, 0, 13), "Rotation": 35, "NbrSpace": 4, "Type": "double_ferry", "color": colors.grey, "city_A": "Sevastopol", "city_B": "Constantinople", "color_name": "grey"})
	_add_path({ "pos": Vector3(34, 0, 11.5), "Rotation": -80, "NbrSpace": 2, "Type": "ferry", "color": colors.grey, "city_A": "Sevastopol", "city_B": "Sochi","color_name": "grey"})
	_add_path({ "pos": Vector3(23, 0, 9.5), "Rotation": -80, "NbrSpace": 3, "Type": "normal", "color": colors.white, "city_A": "Sevastopol", "city_B": "Bucuresti", "color_name": "white"})
	_add_path({ "pos": Vector3(39, 0, 6.5), "Rotation": 0, "NbrSpace": 2, "Type": "normal", "color": colors.grey, "city_A": "Rostov", "city_B": "Sochi", "color_name": "grey"})
	_add_path({ "pos": Vector3(37, 0, 6), "Rotation": 50, "NbrSpace": 3, "Type": "normal", "color": colors.grey, "city_A": "Rostov", "city_B": "Sevastopol", "color_name": "grey"})
	_add_path({ "pos": Vector3(37, 0, 0), "Rotation": -30, "NbrSpace": 2, "Type": "normal", "color": colors.green, "city_A": "Rostov", "city_B": "Kharkov", "color_name": "green"})
	_add_path({ "pos": Vector3(23, 0, -3), "Rotation": 15, "NbrSpace": 5, "Type": "normal", "color": colors.grey, "city_A": "Bucuresti", "city_B": "Kyiv", "color_name": "grey"})
	_add_path({ "pos": Vector3(26, 0, -4), "Rotation": -70, "NbrSpace": 4, "Type": "normal", "color": colors.grey, "city_A": "Kharkov", "city_B": "Kyiv", "color_name": "grey"})
	_add_path({ "pos": Vector3(37, 0, -13), "Rotation": 5, "NbrSpace": 5, "Type": "normal", "color": colors.grey, "city_A": "Kharkov", "city_B": "Moskva", "color_name": "grey"})
	_add_path({ "pos": Vector3(35, 0, -14), "Rotation": 75, "NbrSpace": 2, "Type": "normal", "color": colors.orange, "city_A": "Smolensk", "city_B": "Moskva", "color_name": "orange"})
	_add_path({ "pos": Vector3(28, 0, -10), "Rotation": 45, "NbrSpace": 2, "Type": "normal", "color": colors.red, "city_A": "Smolensk", "city_B": "Kyiv", "color_name": "red"})
	_add_path({ "pos": Vector3(28, 0, -12.5), "Rotation": 100, "NbrSpace": 3, "Type": "normal", "color": colors.yellow, "city_A": "Smolensk", "city_B": "Wilno", "color_name": "yellow"})
	_add_path({ "pos": Vector3(22, 0, -11), "Rotation": -25, "NbrSpace": 2, "Type": "normal", "color": colors.grey, "city_A": "Kyiv", "city_B": "Wilno","color_name": "grey"})
	_add_path({ "pos": Vector3(22, 0, -4), "Rotation": 65, "NbrSpace": 6, "Type": "tunnel", "color": colors.grey, "city_A": "Budapest", "city_B": "Kyiv", "color_name": "grey"})
	_add_path({ "pos": Vector3(14, 0, -10), "Rotation": -70, "NbrSpace": 4, "Type": "normal", "color": colors.grey, "city_A": "Warszawa", "city_B": "Kyiv", "color_name": "grey"})
	_add_path({ "pos": Vector3(11, 0, -9), "Rotation": 35, "NbrSpace": 5, "Type": "normal", "color": colors.blue, "city_A": "Warszawa", "city_B": "Wien", "color_name": "blue"})
	_add_path({ "pos": Vector3(18, 0, -13), "Rotation": 80, "NbrSpace": 2, "Type": "normal", "color": colors.red, "city_A": "Wilno", "city_B": "Warszawa", "color_name": "red"})
	_add_path({ "pos": Vector3(9.5, 0, -12), "Rotation": 85, "NbrSpace": 4, "Type": "normal", "color": colors.pink, "city_A": "Berlin", "city_B": "Warszawa", "color_name": "pink"})
	_add_path({ "pos": Vector3(9.5, 0, -10.5), "Rotation": 85, "NbrSpace": 4, "Type": "normal", "color": colors.yellow, "city_A": "Berlin", "city_B": "Warszawa", "color_name": "yellow"})
	_add_path({ "pos": Vector3(10, 0, -15.5), "Rotation": -25, "NbrSpace": 2, "Type": "normal", "color": colors.grey, "city_A": "Danzig", "city_B": "Warszawa", "color_name": "grey"})
	_add_path({ "pos": Vector3(6, 0, -16), "Rotation": 50, "NbrSpace": 3, "Type": "normal", "color": colors.grey, "city_A": "Berlin", "city_B": "Danzig", "color_name": "grey"})
	_add_path({ "pos": Vector3(-3, 0, -19), "Rotation": 30, "NbrSpace": 4, "Type": "ferry", "color": colors.grey, "city_A": "Kobenhavn", "city_B": "Essen", "color_name": "grey"})
	_add_path({ "pos": Vector3(-4.5, 0, -20), "Rotation": 30, "NbrSpace": 4, "Type": "ferry", "color": colors.grey, "city_A": "Kobenhavn", "city_B": "Essen", "color_name": "grey"})
	_add_path({ "pos": Vector3(2, 0, -27), "Rotation": 50, "NbrSpace": 3, "Type": "normal", "color": colors.yellow, "city_A": "Kobenhavn", "city_B": "Stockholm", "color_name": "yellow"})
	_add_path({ "pos": Vector3(3.5, 0, -25.5), "Rotation": 50, "NbrSpace": 3, "Type": "normal", "color": colors.white, "city_A": "Kobenhavn", "city_B": "Stockholm", "color_name": "white"})
	_add_path({ "pos": Vector3(8, 0, -29), "Rotation": -85, "NbrSpace": 8, "Type": "tunnel", "color": colors.grey, "city_A": "Petrograd", "city_B": "Stockholm", "color_name": "grey"})
	_add_path({ "pos": Vector3(13, 0, -24), "Rotation": 35, "NbrSpace": 3, "Type": "normal", "color": colors.black, "city_A": "Riga", "city_B": "Danzig", "color_name": "black"})
	_add_path({ "pos": Vector3(18, 0, -26), "Rotation": -90, "NbrSpace": 4, "Type": "normal", "color": colors.grey, "city_A": "Riga", "city_B": "Petrograd", "color_name": "grey"})
	_add_path({ "pos": Vector3(28, 0, -24), "Rotation": 35, "NbrSpace": 5, "Type": "normal", "color": colors.blue, "city_A": "Wilno", "city_B": "Petrograd", "color_name": "blue"})
	_add_path({ "pos": Vector3(31, 0, -24), "Rotation": -35, "NbrSpace": 4, "Type": "normal", "color": colors.white, "city_A": "Moskva", "city_B": "Petrograd", "color_name": "white"})
	_add_path({ "pos": Vector3(16, 0, -23), "Rotation": -27, "NbrSpace": 4, "Type": "normal", "color": colors.green, "city_A": "Wilno", "city_B": "Riga", "color_name": "green"})
	add_city({ "name": "Cadiz", "pos": Vector3(-34, 0, 28.5) })
	add_city({ "name": "Lisboa", "pos": Vector3(-39, 0, 24) })
	add_city({ "name": "Barcelona", "pos": Vector3(-24.5, 0, 22.5) })
	add_city({ "name": "Pamplona", "pos": Vector3(-25, 0, 14) })
	add_city({ "name": "Paris", "pos": Vector3(-20, 0, 0) })
	add_city({ "name": "Marseille", "pos": Vector3(-13, 0, 13) })
	add_city({ "name": "Brest", "pos": Vector3(-32, 0, -1.5) })
	add_city({ "name": "Munich", "pos": Vector3(-5.5, 0, -1) })
	add_city({ "name": "London", "pos": Vector3(-24, 0, -13) })
	add_city({ "name": "Madrid", "pos": Vector3(-34, 0, 21) })
	add_city({ "name": "Roma", "pos": Vector3(-3.5, 0, 16) })
	add_city({ "name": "Dieppe", "pos": Vector3(-25, 0, -4) })
	add_city({ "name": "Edinburgh", "pos": Vector3(-29, 0, -26.5) })
	add_city({ "name": "Amsterdam", "pos": Vector3(-16, 0, -12.5) })
	add_city({ "name": "Bruxelles", "pos": Vector3(-18, 0, -8) })
	add_city({ "name": "Frankfurt", "pos": Vector3(-10, 0, -4.5) })
	add_city({ "name": "Zurich", "pos": Vector3(-11, 0, 5) })
	add_city({ "name": "Essen", "pos": Vector3(-9, 0, -11.5) })
	add_city({ "name": "Venezia", "pos": Vector3(-4, 0, 8) })
	add_city({ "name": "Palermo", "pos": Vector3(-0.5, 0, 28) })
	add_city({ "name": "Brindisi", "pos": Vector3(3, 0, 19) })
	add_city({ "name": "Zagrab", "pos": Vector3(2.5, 0, 9) })
	add_city({ "name": "Sarajevo", "pos": Vector3(9.5, 0, 15) })
	add_city({ "name": "Wien", "pos": Vector3(3.5, 0, 0.7) })
	add_city({ "name": "Berlin", "pos": Vector3(-1, 0, -10) })
	add_city({ "name": "Kobenhavn", "pos": Vector3(-3, 0, -21.5) })
	add_city({ "name": "Stockholm", "pos": Vector3(5, 0, -28) })
	add_city({ "name": "Danzig", "pos": Vector3(8.5, 0, -17.5) })
	add_city({ "name": "Budapest", "pos": Vector3(7.5, 0, 3) })
	add_city({ "name": "Sofia", "pos": Vector3(15, 0, 15) })
	add_city({ "name": "Athina", "pos": Vector3(13.5, 0, 26) })
	add_city({ "name": "Warszawa", "pos": Vector3(12, 0, -11) })
	add_city({ "name": "Wilno", "pos": Vector3(21, 0, -13.5) }) 
	add_city({ "name": "Riga", "pos": Vector3(15, 0, -26) })
	add_city({ "name": "Petrograd", "pos": Vector3(29, 0, -26) })
	add_city({ "name": "Moskva", "pos": Vector3(37, 0, -15) })
	add_city({ "name": "Smolensk", "pos": Vector3(30, 0, -12.5) })
	add_city({ "name": "Kyiv", "pos": Vector3(24, 0, -5.5) })
	add_city({ "name": "Kharkov", "pos": Vector3(35.5, 0, -1) })
	add_city({ "name": "Rostov", "pos": Vector3(39, 0, 4) })
	add_city({ "name": "Sochi", "pos": Vector3(39, 0, 12) })
	add_city({ "name": "Sevastopol", "pos": Vector3(31, 0, 11) })
	add_city({ "name": "Bucuresti", "pos": Vector3(20, 0, 9.5) })
	add_city({ "name": "Erzurum", "pos": Vector3(37, 0, 24) })
	add_city({ "name": "Angora", "pos": Vector3(30, 0, 26) })
	add_city({ "name": "Smyrna", "pos": Vector3(20.5, 0, 28.5) })
	add_city({ "name": "Constantinople", "pos": Vector3(24, 0, 21) })
	_add_slots()

func add_city(City):
	City["id"] = Id
	Cities.append(City)
	Id += 1
	var New_city = CityScn.instance()
	add_child(New_city)
	New_city.prepare_city(City)


func _add_path(path):
	path["id"] = Id
	Paths.append(path)
	var New_path = PathScn.instance()
	New_path.id = Id
	Id += 1
	New_path._set_type_path(path["Type"])
	New_path._add_space(path["NbrSpace"], path["color"])
	add_child(New_path)
	Paths_node.append(New_path)
	New_path.translate(path["pos"])
	New_path.rotate_y(deg2rad(path["Rotation"]))

func _add_slots():
	var CardSlotScn = preload("res://Scene/Object/card_location.scn")
	for i in range(5):
		var slot = CardSlotScn.instance()
		slot.set_translation(Vector3(45,0,-10 + (i*5)))
		Slots.append(slot)
		add_child(slot)
